# Generated by Django 4.2.1 on 2023-12-31 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('description', models.TextField(verbose_name='Информация')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена занятия')),
                ('img_main', models.ImageField(upload_to='img', verbose_name='Главная картина')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Дополнительная картина')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Дополнительная картина')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Дополнительная картина')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Дополнительная картина')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Дополнительная картина')),
            ],
            options={
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='преподаватель')),
                ('name_prof', models.CharField(max_length=100, verbose_name='профессия')),
                ('tel', models.CharField(max_length=60, verbose_name='телефон')),
                ('description', models.TextField(blank=True, verbose_name='Информация')),
                ('img_main', models.ImageField(upload_to='img', verbose_name='Фото')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'преподаватель',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.activity')),
            ],
            options={
                'verbose_name_plural': 'расписания занятий',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher', verbose_name='преподаватель'),
        ),
    ]
