# Generated by Django 4.2.1 on 2023-12-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_zanyatie_alter_teacher_tel_activity_zanyat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zanyatie',
            options={'verbose_name_plural': 'Вид занятии'},
        ),
    ]
