# Generated by Django 4.2.1 on 2023-12-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_zanyatie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('comments', models.TextField(verbose_name='Комментарии')),
            ],
            options={
                'verbose_name_plural': 'Записи на занятии',
            },
        ),
    ]
