# Generated by Django 4.2.1 on 2023-12-31 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.activity', verbose_name='Название занятия'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher', verbose_name='Преподаватель'),
        ),
    ]
